apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels: 
    {{- toYaml .Values.deploymentLabels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      {{- toYaml .Values.podLabels | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- toYaml .Values.podLabels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}