apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- toYaml .Values.podLabels | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.port.name }}
    port: {{ .Values.service.port.port }}
    protocol: {{ .Values.service.port.protocol }}
    nodePort: {{ .Values.service.port.nodePort }}
  