[webservers]

web-1 ansible_host=158.160.109.41 fqdn=fhmknt1n0a9cqgngl26q.auto.internal

web-2 ansible_host=158.160.105.205 fqdn=fhmpqnb4jletoci34te6.auto.internal


[databases]

main ansible_host=158.160.101.102 fqdn=fhm3tjf8of8jmp4b93a8.auto.internal

replica ansible_host=158.160.33.32 fqdn=fhmlljlfri4ge1l1lsqs.auto.internal


[storage]

storage ansible_host=89.169.142.36 fqdn=fhmturc4pef97pupe4pj.auto.internal
