FROM python:3.9-slim

WORKDIR /app

ARG DB_HOST="localhost"
ARG DB_USER="app"
ARG DB_PASSWORD=""
ARG DB_NAME=""

ENV DB_HOST=${DB_HOST}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}

COPY . .
RUN python -m pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "main.py"]

